### ISSUE TITLE
Minor audio stutter/hitching with frame skip set to 0

### ISSUE THREAD

**Issue by BParks21** [punesemu/puNES#52] opened 2017-11-15 13:20 UTC
As the title says. It's very difficult to notice though. I was wrong, still micro stutter and frame pacing issue with default frame skip setting. Frame skip set to 0 is silky smooth but has these faint audio hitches.

**Comment by WizLizard** [comment] 2017-12-24 08:32
@punesemu Any news on a fix for this?

**Comment by Raziel-01** [comment] 2018-10-09 16:41
@ BParks21 : Hi ! i've got the same issues (puNES 0.102) : if the frameskip option is set to "default", i've got micro scrolling problem. If i put "0" to frameskip, the scrolling is perfect, but i encounter audio glitches (vsync on).
It's also impossible without Vsync (tearing !!!).

Did you solve the problems ? Anyone else has a solution ?

Thanks for answering.

**Comment by punesemu** [comment] 2018-10-09 20:10
Hmmm, the problem is that I can't reproduce the problem. First can you tell me what version do you use? Windows? Linux? x86? x64? OpenGL? D3D9?

**Comment by Raziel-01** [comment] 2018-10-12 10:29
I use the D3D9 version 64 bits (puNES 0.102) - windows (i'm on windows 7 - 64 bits).

I try puNES 0.103 (commit r977) on D3D9 version and SDL also => i can't put 0 to frameskip cause the option is automatically changed to 2 !!! I can put it on "default" and it will stay on it, but in this case, i got some minor scrolling problem (like a little "jump" into the horizontal scrolling) : il's light but it's still here.
Same if i keep frameskip on 2.

I make all the updates about video driver (GTX 980) and sound driver (Asus xonar D1) but it doesn't change.

**Comment by unit3uk** [comment] 2018-10-12 23:43
I have the same problem with puNES 0.102 (64bit-d3d version).  If I select "VSync" and "Frame Skip" set to "0", I hear an occasional crackling/popping sound.  I'm using Windows 7, 64-bit.

**Comment by punesemu** [comment] 2018-10-13 07:39
> I try puNES 0.103 (commit r977) on D3D9 version and SDL also => i can't put 0 to frameskip cause the option is automatically changed to 2 !!!

Thanks for the report, I've already fixed in https://github.com/punesemu/puNES/commit/5f9b2228f421b42f9e0d3c7c7be28f6052026880
I really hope to be able to reproduce the problem in order to solve it. I will keep you informed

**Comment by punesemu** [comment] 2018-10-19 19:17
You can try with this version? [punes.exe](https://www.dropbox.com/s/f9ja5pfngwk3hz9/punes.exe?dl=0). Consider that could be an unstable version, I'm working heavily on it.

**Comment by Raziel-01** [comment] 2018-10-21 14:14
I try your .exe (0.103 commit978) : i can put 0 on frameskip and there is no more sound bug, but while horizontal scrolling, there is sometimes video hitching (synchro problem ?) : i record the beginning of castelvania, and you can see what happens : [http://www.k-upload.fr/afficher-fichier-2018-10-21-145b50825castlevaniap.avi.html](url)

I really appreciate you try to resolve that anyway ! i keep hope :)

**Comment by Raziel-01** [comment] 2018-11-13 11:48
Hi !
I try the last WIP yesterday : ok for audio (I selected 0 to audio buffer) : i still got a little "jump" into the horizontal scrolling second every 10 seconds.
It's not Vsync cause it's activated (without it, it's unplayable => tearing).

It seems that audio/video sync is not perfect so this "jump" is the consequence ...

I would try it on another PC (different OS) to see if i can reproduce that or no.

**Comment by punesemu** [comment] 2020-11-18 08:12
No other info.

**Closed by punesemu** 2020-11-18 08:12 UTC
