### ISSUE TITLE
Square 1 channel is off by default

### ISSUE THREAD

**Issue by EhGuppy** [punesemu/puNES#187] opened 2022-01-10 21:48 UTC
When I start a game, the square 1 audio channel is always off. All of my config settings save normally, but no matter what I do, square 1 is off and I have to go into the settings and turn it on. I checked the config file and all of the apu channels are set to be on at 100%, I even took that out and had it generate a new config file, and it still starts turned off. Definitely want to get this working, puNES seems to be the best emulator to use with ReShade.

**Comment by punesemu** [comment] 2022-01-10 23:01
Hi, can you give me some more information? What version do you use? What OS? Linux? Windows OpenGL? Windows D3D9? 64 bit? 32 bit? Can you send me your cfg file too? The more news you give me, the more chances are that I will be able to solve the problem.

**Comment by ResoundingSounds** [comment] 2022-01-10 23:38
0.108 64-bit OpenGL, on Windows 10. I also tried it with the ReShade components removed just to be sure. Config settings should be default except pixel aspect ratio (set to 1:1). Thanks for checking out the issue, let me know if anything else would be helpful 👍 
[puNES.txt](https://github.com/punesemu/puNES/files/7842539/puNES.txt)

**Comment by punesemu** [comment] 2022-01-11 07:38
I can't reproduce your problem. If you want I could do a remote assistance on your computer and I could try to understand what happens. Contact me at punes.development@gmail.com if you agree.

**Comment by ResoundingSounds** [comment] 2022-01-11 08:21
I tried troubleshooting it myself just now, and I got it to work. But I still don't have an answer to what caused it. 

I downloaded a fresh copy of the emulator and started it, still had the same problem, but then I remembered that it's grabbing settings from the folder in 'Documents', so I grabbed that and stuck it somewhere else so it'd generate fresh files. Tried the emulator again, and the square channel is now on by default.

I checked out the folder I stuck away, and the only things in there are a couple files in the 'jsc' folder, a couple more in the 'pgs' folder, and the config files (input, puNES, recent) in the root folder. I was thinking something went wrong with the puNES config file, so I swapped the new one with that one just to see if it would cause the problem again, but it didn't.

So yeah I got it working, but not sure why it happened in the first place.
Feel free to close the issue unless you're curious to find out what the issue was, but it was probably just something weird that happened on my end. Thanks again for troubleshooting :)

**Comment by punesemu** [comment] 2022-01-11 08:47
You are welcome.

**Comment by liurui39660** [comment] 2022-06-12 13:35
I met the same issue, but I found that in `input.cfg`, section `shortcuts`, if `joystick GUID` is set, or say, not `NULL`, then this issue occurs.

**Comment by punesemu** [comment] 2022-06-12 21:17
Many thx for the info, I will try to replicate the problem.

**Comment by punesemu** [comment] 2022-06-13 14:29
I can't reproduce the problem. Can you send yours "input.cfg" and "puNES.cfg"?

**Comment by liurui39660** [comment] 2022-06-13 14:31
[cfg.zip](https://github.com/punesemu/puNES/files/8891927/cfg.zip)

**Comment by punesemu** [comment] 2022-06-13 14:32
Thx.

**Comment by liurui39660** [comment] 2022-06-14 04:06
Confirm resolved on 64bit OpenGL WIP build.
Thanks for help, I think the issue can be closed now.

**Comment by punesemu** [comment] 2022-06-14 05:17
Thx for the help.

**Closed by punesemu** 2022-06-14 05:17 UTC
